INSERT INTO EXAMPLE (name) VALUES ('ENTERNAME');
INSERT INTO EXAMPLE (name) VALUES ('ENTERNAME');
INSERT INTO EXAMPLE (name, EXAMPLE) VALUES ('ENTERNAME', true);
INSERT INTO EXAMPLE (name, EXAMPLE) VALUES ('ENTERNAME ENTERNAME', true);
INSERT INTO EXAMPLE (name, EXAMPLE) VALUES ('ENTERNAME ENTERNAME', true);
INSERT INTO EXAMPLE (name) VALUES ('ENTERNAME');
